### ISSUE TITLE
Unable to generate images on 2021

### ISSUE THREAD

**Issue by clinew** [latex2html/latex2html#70]
Upgraded from what I believe was 2017 to 2021 and image-generation is broken with an arcane message:

```
Preview: Fontsize 10pt
Preview: PDFoutput 1

latex2htmlLength hsize=349.0pt

latex2htmlLength vsize=633.0pt

latex2htmlLength hoffset=0.0pt

latex2htmlLength voffset=0.0pt

latex2htmlLength topmargin=0.0pt

latex2htmlLength topskip=0.00003pt

latex2htmlLength headheight=0.0pt

latex2htmlLength headsep=0.0pt

latex2htmlLength parskip=0.0pt plus 1.0pt

latex2htmlLength oddsidemargin=62.0pt

latex2htmlLength evensidemargin=62.0pt


:makeimage20:lthtmlCropMarkHeight:=157.20949pt

:makeimage20:lthtmlCropMarkDepth:=0.0pt:1ex:=4.30554pt
Preview: Tightpage -32891 -32891 32891 32891
! Undefined control sequence.
\pr@endbox ...fi \c@page =\pr@snippet \pr@shipout 
                                                  \ifpr@fixbb \hbox {\dimen@...
l.216 \lthtmldisplayZ
                     
! Undefined control sequence.
\@outputpage ...istfalse \@parboxrestore \shipout 
                                                  \vbox {\set@typeset@protec...
l.217 \lthtmlcheckvsize\clearpage
                                 }
! Undefined control sequence.
\@outputpage ...istfalse \@parboxrestore \shipout 
                                                  \vbox {\set@typeset@protec...
l.217 \lthtmlcheckvsize\clearpage
                                 }
    <snip>
! Output loop---100 consecutive dead cycles.
\clearpage ...rite \m@ne {}\vbox {}\penalty -\@Mi 
                                                  
l.217 \lthtmlcheckvsize\clearpage
                                 }
[98{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
! Undefined control sequence.
\@outputpage ...istfalse \@parboxrestore \shipout 
                                                  \vbox {\set@typeset@protec...
l.219 {\newpage
               \clearpage
! Undefined control sequence.
\@outputpage ...istfalse \@parboxrestore \shipout 
                                                  \vbox {\set@typeset@protec...
l.219 {\newpage\clearpage
                         
(That makes 100 errors; please try again.)
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on images.log.
Debug (syswait): Finished child process: #884
 at /usr/lib64/latex2html/latex2html.pl line 3795.

 *** processing  images ***

Transforming PDF images using gs/png16m ...
/usr/bin/gs -q -dNOPAUSE -dNO_PAUSE -dBATCH -dNOSAFER -sDEVICE=png16m -r240 -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -sOutputFile=/tmp/l2h873/image%d.png ./images.pdfDebug (syswait): Running "/usr/bin/gs -q -dNOPAUSE -dNO_PAUSE -dBATCH -dNOSAFER -sDEVICE=png16m -r240 -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -sOutputFile=/tmp/l2h873/image%d.png ./images.pdf"
 at /usr/lib64/latex2html/latex2html.pl line 3882.
Error: /undefinedfilename in (./images.pdf)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:743/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.53.3: Unrecoverable error, exit code 1
Debug (syswait): Finished child process: #913
 at /usr/lib64/latex2html/latex2html.pl line 3882.
Error: 
No such file or directory at /usr/lib64/latex2html/latex2html.pl line 4238.
Compilation failed in require at /usr/bin/latex2html line 39.
make: *** [makefile:34: tutor] Error 2
```
I tried throwing around various combinations of `-image_type png` and `-nouse_pdftex`, but nothing seemed to help.  Any ideas how to triage this?

If it helps, source is here: https://github.com/clinew/www.frostsnow.net.git and the fastest compile command is 'make clean && make tutor'.

**Comment by danielgildea** [comment]
This file works for me if I remove the following from .latex2html-init:

`
$LATEX_COLOR = "\\pagecolor[RGB]{217, 217, 217}";
`

This is a workaround for a bug that has been fixed now.

**Comment by clinew** [comment]
I tried commenting that line out and also fully removing that line and am having the same issue.  This might be an unsatisfied dependency issue then.  I'll play around with `USE` flags and see if I can dig up anything.

**Comment by clinew** [comment]
I can reproduce the issue by running `pdflatex images.tex` (`images.tex`: http://www.frostsnow.net/files/images.tex).  Does the same thing happen for you?

**Comment by clinew** [comment]
I ran a `git bisect` and came across `f4fd56799fddda8c62e1513aded4b172fd941983` as the first bad commit.  Trying to decipher it now, but will probably go to bed before I can figure it out.

**Comment by danielgildea** [comment]
> I can reproduce the issue by running `pdflatex images.tex` (`images.tex`: http://www.frostsnow.net/files/images.tex). Does the same thing happen for you?

`pdflatex images.tex` works for me - here are the logs.
[images.pdf](https://github.com/latex2html/latex2html/files/6809518/images.pdf)
[images.log](https://github.com/latex2html/latex2html/files/6809524/images.log)
[images.stdout.txt](https://github.com/latex2html/latex2html/files/6809528/images.stdout.txt)

**Comment by clinew** [comment]
That makes absolutely no sense.  What does the following command give for you:
```
$ ldd $(which pdftex)
        linux-gate.so.1 (0xb7f27000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0xb7c47000)
        libz.so.1 => /lib/libz.so.1 (0xb7c2e000)
        libkpathsea.so.6 => /usr/lib/libkpathsea.so.6 (0xb7c12000)
        libstdc++.so.6 => /usr/lib/gcc/i686-pc-linux-gnu/10.3.0/libstdc++.so.6 (0xb7a48000)
        libm.so.6 => /lib/libm.so.6 (0xb798b000)
        libgcc_s.so.1 => /usr/lib/gcc/i686-pc-linux-gnu/10.3.0/libgcc_s.so.1 (0xb796f000)
        libc.so.6 => /lib/libc.so.6 (0xb77a0000)
        /lib/ld-linux.so.2 (0xb7f29000)
```
The only other obvious thing I see is that the version you are running is slightly older:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex 2021.2.15)  13 JUL 2021 10:13
```
```
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021 Gentoo Linux) (preloaded format=pdflatex 2021.6.12)  13 JUL 2021 01:07
```
Using my version, if I take `f4fd56799fddda8c62e1513aded4b172fd941983` and apply this patch:
```
diff --git a/latex2html.pin b/latex2html.pin
index 7b767d5..5268379 100755
--- a/latex2html.pin
+++ b/latex2html.pin
@@ -7125,17 +7125,17 @@ sub make_latex{
     " \\def\\phantompar{\\csname par\\endcsname}\\normalsize}%\n" .
     "\\def\\lthtmltypeout#1{{\\let\\protect\\string \\immediate\\write\\lthtmlwrite{#1}}}%\n" .
     (($USE_DVIPNG || $IMAGE_TYPE eq 'svg') ? <<'</dvipng>' :
-\usepackage[tightpage,active]{preview}
+\usepackage[tightpage]{preview}
 \newbox\lthtmlPageBox
 \newdimen\lthtmlCropMarkHeight
 \newdimen\lthtmlCropMarkDepth
 \long\def\lthtmlTightVBox#1#2{%
-    \setbox\lthtmlPageBox\vbox{\hbox{\catcode`\_=8 #2}}%
+    \setbox\lthtmlPageBox\vbox{\catcode`\_=8 #2}%
     \lthtmlCropMarkHeight=\ht\lthtmlPageBox \advance \lthtmlCropMarkHeight 6pt
     \lthtmlCropMarkDepth=\dp\lthtmlPageBox
     \lthtmltypeout{^^J:#1:lthtmlCropMarkHeight:=\the\lthtmlCropMarkHeight}%
     \lthtmltypeout{^^J:#1:lthtmlCropMarkDepth:=\the\lthtmlCropMarkDepth:1ex:=\the \dimexpr 1ex}%
-    \begin{preview}\copy\lthtmlPageBox\end{preview}}}%
+    \begin{preview}\copy\lthtmlPageBox\end{preview}}
 \long\def\lthtmlTightFBox#1#2{%
     \adjustnormalsize\setbox\lthtmlPageBox=\vbox\bgroup %
     \let\ifinner=\iffalse \let\)\liih@math %
```
...then the command "works" in that it generates images, but the images are sized to an entire page so it's not acceptable output.  Adding `active` as a package option generates the stream of `Undefined control sequence` seen earlier while adding `hbox` gives... what looks likes some kind of... scoping error from a missing brace?  File contents are:
"Working": https://www.frostsnow.net/files/working.tar
With `active`: https://www.frostsnow.net/files/active.tar
With `hbox`: https://www.frostsnow.net/files/hbox.tar

**Comment by danielgildea** [comment]
If we get different results on the same images.tex, it probably has to do with the verisons of the various latex packages.  Your original images.tex works for me with texlive 2020, texlive 2021, and the current texlive repositories.  Your package versions don't exactly match any of those.  One suggestion would be to make sure all your packages come from the same version of texlive.  I'd also be curious whether images work for you in a simple latex file without using the forest/graphicx/html packages.

**Comment by clinew** [comment]
I'm using the distro-provided version of texlive without anything weird added in.  It's not clear how I'd go about modifying it and all its dependencies without extraordinary effort.

I tried the images in a plain LaTeX file and it runs just fine (`plain.*`), but it breaks with one of the same errors as soon as I include the `preview` package (`plain-preview.*`).  https://www.frostsnow.net/files/plain.tar.bz2

**Comment by danielgildea** [comment]
There is a bug report at gentoo regarding incompatible versions of preview and tikz.
https://bugs.gentoo.org/800827

Closing this issue as it does not seem to be a problem with latex2html.

**Comment by clinew** [comment]
Nice find!  I managed to install a newer version of `pgf` and it seems to (mostly) work.  A few defaults were changed which is causing problems; will see if I can fix them before filing any additional issues.
